### ISSUE TITLE
Gaze Detection and Center Viewport Restriction

### ISSUE THREAD

**Issue by sidrao2006** [sudarshansudarshan/cal#21]
- [x] Configure a model for gaze detection and center viewport restriction
- [x] Create a simple React component which implements this functionality

Requirements: 

- Should track (as boolean) whether or not the user's face is within the center viewport.
- Signal a violation if the check failure crosses a threshold

**Comment by AllyNav** [comment]
@sidrao2006 please update to me the changes you have done for gaze detectioon.

**Comment by sidrao2006** [comment]
@AllyNav I'm on leave today. I'll be back tomorrow and we can discuss this then or please talk to @akashreactdeveloper regarding this.
