### ISSUE TITLE
Setup docker configuration

### ISSUE THREAD

**Issue by adityabmv** [sudarshansudarshan/cal#29]

**Comment by sidrao2006** [comment]
I have set up Dev containers for backend and frontend.
To use the new setup simply open the folders `backend-cal` and `frontend-cal` either in vs code or in Code spaces and click on the reopen in container prompt
If this does not show up please ensure you have the dev containers extension installed.

If any additional programs or VS code extensions are required to be added, please post a comment on this issue with the name of the software / Vs code extension ID
