### ISSUE TITLE
Add a License to the repository 

### ISSUE THREAD

**Issue by sidrao2006** [sudarshansudarshan/cal#64]

**Comment by Kapil-Mulay-1421** [comment]
All the dependencies used in this project have the MIT license, except the following: 
Back-end: 
django, djangorestframework - BSD3
psycopg2-binary - LGPL-3.0

Front-end:
tfjs and mediapipe - Apache2.0

Seeing as none of these licenses are restrictive in terms of the license we can add to our project, we should be able to add the license of our choice.
