### ISSUE TITLE
Audio Processing Component Does Not Request Microphone Permission on First Load

### ISSUE THREAD

**Issue by Kapil-Mulay-1421** [sudarshansudarshan/cal#94]
#### Description

The React component designed for voice activity detection does not request microphone permissions on the first load. On initial page load, the microphone permission prompt is not displayed, and the component does not function correctly. However, when the page is refreshed, the permission is requested, and the component works as expected. This issue persists in environments where user interaction is not explicitly required.

#### Expected Behavior

- The browser should request microphone permissions automatically when the component is first loaded.
- The `AudioContext` should initialize and resume without requiring a manual page reload or explicit user interaction.

#### Observed Behavior

- On the first load, the microphone permission prompt does not appear, and the component does not function.
- After a page reload, the permission is requested, and the component starts working.

#### Steps to Reproduce

1. Integrate the provided `VoiceActivityDetection` component into a React application.
2. Load the page for the first time.
3. Observe that no microphone permission prompt is displayed.
4. Refresh the page.
5. Observe that the permission is requested, and the component functions as expected.

#### Possible Cause

- Modern browsers require a user interaction (e.g., a click or keypress) to resume an `AudioContext` if it is in a "suspended" state upon initialization.
- The `getUserMedia` API might not be invoked properly during the initial page load due to timing or browser restrictions.

#### Proposed Solution

1. **Automatically Request Permissions**:
   - Call `navigator.mediaDevices.getUserMedia` during the component's mount phase to trigger the browser's permission prompt immediately.

2. **Handle Suspended AudioContext**:
   - Resume the `AudioContext` on the first user interaction if it remains suspended.

3. **Fallback for Browser Restrictions**:
   - Attach event listeners (e.g., `click`, `keydown`) to resume the `AudioContext` if it is not automatically activated.

**Comment by adityasoni04** [comment]
I am interested to resolve this issue.

**Comment by Kapil-Mulay-1421** [comment]
This issue is not open to developer applicants. Please please not that you are only allowed to work on issues labelled "developer-applicant".
